<a href="https://colab.research.google.com/github/KilluaZ01/DataScience/blob/main/ImdbVocab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras
data = keras.datasets.imdb
from tensorflow.keras.preprocessing import text, sequence
import os
import numpy as np

In [ ]:
# These are the Constant Values

VOCAB_SIZE = 88000
MAXLEN = 250
BATCH_SIZE = 64

In [ ]:
(train_data, train_labels), (test_data, test_labels) = data.load_data(num_words= VOCAB_SIZE)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
train_data = sequence.pad_sequences(train_data, MAXLEN)
test_data = sequence.pad_sequences(test_data, MAXLEN)

In [ ]:
model = keras.Sequential([
    keras.layers.Embedding(VOCAB_SIZE, 32),
    keras.layers.LSTM(32),
    keras.layers.Dense(1, activation = 'sigmoid')
])

In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(train_data, train_labels, epochs = 10, validation_split= 0.2)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step - accuracy: 0.9981 - loss: 0.0077 - val_accuracy: 0.9900 - val_loss: 0.0310
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.9990 - loss: 0.0056 - val_accuracy: 0.9952 - val_loss: 0.0147
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 8s 13ms/step - accuracy: 0.9950 - loss: 0.0185 - val_accuracy: 0.9932 - val_loss: 0.0212
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step - accuracy: 0.9962 - loss: 0.0133 - val_accuracy: 0.9890 - val_loss: 0.0382
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.9972 - loss: 0.0090 - val_accuracy: 0.9910 - val_loss: 0.0266
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 9s 13ms/step - accuracy: 0.9999 - loss: 8.0430e-04 - val_accuracy: 0.9914 - val_loss: 0.0318
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 1.0000 - loss: 1.4403e-04 - val_accuracy: 0.9906 - val_loss: 0.0350
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 1.0000 - loss: 7.090

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 250, 32)        │     2,816,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 32)             │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,473,061 (32.32 MB)

 Trainable params: 2,824,353 (10.77 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,648,708 (21.55 MB)

In [ ]:
results = model.evaluate(test_data, test_labels, verbose = 2)

782/782 - 5s - 7ms/step - accuracy: 0.8492 - loss: 1.2223


In [ ]:
2824354 * 2

5648708

In [ ]:
word_index = data.get_word_index()

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
def encode_text(text):
  tokens = keras.preprocessing.text.text_to_word_sequence(text)
  tokens = [word_index[word] if word in word_index else 0 for word in tokens]
  return sequence.pad_sequences([tokens], MAXLEN)[0]

In [ ]:
text = 'that movie was so amazing, so amazing'
encoded = encode_text(text)
print(encoded)

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  12  17  13  3

In [ ]:
rev_word_indexing = {value:key for key, value in word_index.items()}

In [ ]:
word_index[0] = '<PAD>'

In [ ]:
def reverse_word_index(text_rev):
  list_decode = []
  for i in range(len(text_rev)):
    list_decode.append(rev_word_indexing.get(text_rev[i]))
  return list_decode

reverse_word_index(encoded)

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,

In [ ]:
def decode_integer(integers):
  PAD = 0
  text = ''
  for num in integers:
    if num!= PAD:
      text += rev_word_indexing[num] + ' '

  return text

text_prediction = decode_integer(encoded)

In [ ]:
def predict(text):
  encoded_text = encode_text(text)
  pred = np.zeros((1, 250))
  pred[0] = encoded_text
  result = model.predict(pred)
  return result

predict(text_prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[0.98086435]], dtype=float32)

In [ ]:
model.predict(np.arange(250).reshape(1,250))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0.9772094]], dtype=float32)

In [ ]:
positive_review = 'Good movie, I loved it, I will watch it again'
predict(positive_review)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.91157037]]


In [ ]:
negative_review = 'Bad movie, I hated it, I wont watch it again,'
predict(negative_review)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[0.11257794]], dtype=float32)

In [ ]:
def prediction_function(user_review):
  prediction = predict(user_review)
  print(user_review)
  if prediction[0] > 0.62:
    print('Good Review')
  else:
    print('Bad Review')

user_review = input('Enter your review: ')
prediction_function(user_review)

Enter your review: Nice movie
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
Nice movie
Good Review
